// Configuration - Auto-loaded from config.js (generated by Terraform)
// Fallback values if config.js fails to load
const CONFIG = window.APP_CONFIG || {
    API_URL: 'https://pii-api.sebekgo.com',
    BUCKET_NAME: 'YOUR_BUCKET_NAME',
    REGION: 'us-west-2'
};

// State
let selectedFile = null;
let redactedData = null;

// Initialize
document.addEventListener('DOMContentLoaded', () => {
    initializeEventListeners();
    loadConfigFromURL();
    initializeAWS();
});

function initializeAWS() {
    // Try to use credentials from environment or prompt user
    // For testing, you can set credentials here temporarily
    
    // Option 1: Use environment credentials (requires AWS CLI configured)
    // This won't work in browser without Cognito
    
    // Option 2: Prompt for credentials (TEMPORARY - not for production)
    const accessKey = localStorage.getItem('aws_access_key');
    const secretKey = localStorage.getItem('aws_secret_key');
    
    if (accessKey && secretKey) {
        AWS.config.update({
            accessKeyId: accessKey,
            secretAccessKey: secretKey,
            region: CONFIG.REGION
        });
        console.log('AWS credentials loaded from localStorage');
    } else {
        console.warn('AWS credentials not configured. Upload will fail.');
        console.log('To configure, run in browser console:');
        console.log('localStorage.setItem("aws_access_key", "YOUR_ACCESS_KEY");');
        console.log('localStorage.setItem("aws_secret_key", "YOUR_SECRET_KEY");');
        console.log('Then reload the page.');
    }
}

function initializeEventListeners() {
    const fileInput = document.getElementById('fileInput');
    const uploadArea = document.getElementById('uploadArea');

    // File input change
    fileInput.addEventListener('change', (e) => {
        handleFileSelect(e.target.files[0]);
    });

    // Drag and drop
    uploadArea.addEventListener('dragover', (e) => {
        e.preventDefault();
        uploadArea.classList.add('dragover');
    });

    uploadArea.addEventListener('dragleave', () => {
        uploadArea.classList.remove('dragover');
    });

    uploadArea.addEventListener('drop', (e) => {
        e.preventDefault();
        uploadArea.classList.remove('dragover');
        const file = e.dataTransfer.files[0];
        if (file) handleFileSelect(file);
    });

    // Click to upload
    uploadArea.addEventListener('click', () => {
        fileInput.click();
    });
}

function loadConfigFromURL() {
    // Allow config via URL parameters for easy setup
    const params = new URLSearchParams(window.location.search);
    if (params.has('bucket')) CONFIG.BUCKET_NAME = params.get('bucket');
    if (params.has('api')) CONFIG.API_URL = params.get('api');
}

function handleFileSelect(file) {
    if (!file) return;

    const validTypes = ['.pdf', '.txt', '.json', '.csv'];
    const fileExt = '.' + file.name.split('.').pop().toLowerCase();

    if (!validTypes.includes(fileExt)) {
        showStatus('Invalid file type. Please upload PDF, TXT, JSON, or CSV files.', 'error');
        return;
    }

    selectedFile = file;
    document.getElementById('fileName').textContent = `${file.name} (${formatBytes(file.size)})`;
    document.getElementById('fileInfo').classList.remove('hidden');
    document.getElementById('uploadBtn').disabled = false;
    document.getElementById('uploadArea').style.display = 'none';
    hideStatus();
    document.getElementById('downloadCard').classList.add('hidden');
}

function clearFile() {
    selectedFile = null;
    redactedData = null;
    document.getElementById('fileInput').value = '';
    document.getElementById('fileInfo').classList.add('hidden');
    document.getElementById('uploadBtn').disabled = true;
    document.getElementById('uploadArea').style.display = 'block';
    document.getElementById('downloadCard').classList.add('hidden');
    hideStatus();
}

async function uploadFile() {
    if (!selectedFile) return;

    if (CONFIG.BUCKET_NAME === 'YOUR_BUCKET_NAME') {
        showStatus('Please configure the bucket name in app.js', 'error');
        return;
    }

    try {
        setLoading(true);
        showProgress(0);

        // Step 1: Upload to S3
        showStatus('Uploading file to S3...', 'info');
        await uploadToS3(selectedFile);
        showProgress(33);

        // Step 2: Request redaction
        showStatus('Processing and redacting PII...', 'info');
        const redactedContent = await requestRedaction(selectedFile.name);
        showProgress(66);

        // Step 3: Prepare download
        redactedData = {
            content: redactedContent,
            filename: `redacted-${selectedFile.name}`,
            type: selectedFile.type
        };
        showProgress(100);

        // Show success
        setTimeout(() => {
            showStatus('Redaction complete!', 'success');
            showDownloadCard();
            hideProgress();
        }, 500);

    } catch (error) {
        console.error('Error:', error);
        showStatus(`Error: ${error.message}`, 'error');
        hideProgress();
    } finally {
        setLoading(false);
    }
}

async function uploadToS3(file) {
    // Check if AWS credentials are configured
    if (!window.AWS || !window.AWS.config.credentials) {
        throw new Error('AWS credentials not configured. Please set up AWS credentials first.');
    }
    
    const s3 = new AWS.S3();
    
    const params = {
        Bucket: CONFIG.BUCKET_NAME,
        Key: file.name,
        Body: file,
        ContentType: file.type
    };
    
    try {
        await s3.putObject(params).promise();
        console.log('File uploaded to S3:', file.name);
    } catch (error) {
        console.error('S3 upload error:', error);
        throw new Error(`Upload failed: ${error.message}`);
    }
}

async function requestRedaction(filename) {
    // Check if AWS credentials are configured
    if (!window.AWS || !window.AWS.config.credentials) {
        throw new Error('AWS credentials not configured. Please set up AWS credentials first.');
    }

    const url = `${CONFIG.API_URL}/${CONFIG.BUCKET_NAME}/${filename}`;
    
    // Create AWS Signature V4 signed request
    const endpoint = new AWS.Endpoint(CONFIG.API_URL.replace('https://', ''));
    const request = new AWS.HttpRequest(endpoint, CONFIG.REGION);
    request.method = 'GET';
    request.path = `/${CONFIG.BUCKET_NAME}/${filename}`;
    request.headers.Host = endpoint.host;
    
    // Sign the request
    const signer = new AWS.Signers.V4(request, 'execute-api');
    signer.addAuthorization(AWS.config.credentials, new Date());
    
    // Execute signed request
    const response = await fetch(url, {
        method: 'GET',
        headers: request.headers
    });
    
    if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`API error ${response.status}: ${errorText}`);
    }
    
    // Check content type to determine how to parse
    const contentType = response.headers.get('content-type');
    
    if (contentType && contentType.includes('application/json')) {
        // JSON response (likely a PDF or error)
        const data = await response.json();
        
        // Handle base64 encoded content (PDFs)
        if (data.isBase64Encoded) {
            return atob(data.body);
        }
        
        return data.body || data;
    } else {
        // Plain text response (TXT, CSV, etc.)
        return await response.text();
    }
}

function downloadRedacted() {
    if (!redactedData) return;

    const blob = new Blob([redactedData.content], { type: redactedData.type || 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = redactedData.filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    showStatus('Download started!', 'success');
}

// UI Helper Functions
function setLoading(loading) {
    const btn = document.getElementById('uploadBtn');
    const btnText = document.getElementById('uploadBtnText');
    const spinner = document.getElementById('uploadSpinner');

    btn.disabled = loading;
    if (loading) {
        btnText.textContent = 'Processing...';
        spinner.classList.remove('hidden');
    } else {
        btnText.textContent = 'Upload & Redact';
        spinner.classList.add('hidden');
    }
}

function showStatus(message, type = 'info') {
    const statusEl = document.getElementById('statusMessage');
    statusEl.textContent = message;
    statusEl.className = `status-message ${type}`;
    statusEl.classList.remove('hidden');
}

function hideStatus() {
    document.getElementById('statusMessage').classList.add('hidden');
}

function showProgress(percent) {
    const progressBar = document.getElementById('progressBar');
    const progressFill = document.getElementById('progressFill');
    progressBar.classList.remove('hidden');
    progressFill.style.width = `${percent}%`;
}

function hideProgress() {
    setTimeout(() => {
        document.getElementById('progressBar').classList.add('hidden');
        document.getElementById('progressFill').style.width = '0%';
    }, 500);
}

function showDownloadCard() {
    const card = document.getElementById('downloadCard');
    const stats = document.getElementById('redactionStats');
    
    stats.innerHTML = `
        <strong>File:</strong> ${redactedData.filename}<br>
        <strong>Size:</strong> ${formatBytes(redactedData.content.length)}<br>
        <strong>Status:</strong> All PII redacted successfully
    `;
    
    card.classList.remove('hidden');
    card.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
}

function formatBytes(bytes) {
    if (bytes === 0) return '0 Bytes';
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return Math.round(bytes / Math.pow(k, i) * 100) / 100 + ' ' + sizes[i];
}
