// Auto-generated configuration - DO NOT EDIT MANUALLY
// This file is generated by Terraform with actual deployment values

window.APP_CONFIG = {
    API_URL: '${api_url}',
    BUCKET_NAME: '${bucket_name}',
    REGION: '${region}'
};

console.log('Configuration loaded:', window.APP_CONFIG);
